spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planery?characterEncoding=UTF-8&serverTimezone=UTC
    username: planery
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  key: S7W8YV7zcK6p+Ur0l2FnVHlHO11KI1vjwDrrPUwnHy4=