spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/planery?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  key: ${JWT_KEY}